using System;
using System.Collections.Generic;
using System.Text;

namespace ItsUmbria.Junk
{
    public class WorstCaseCamion
    {
        private static WorstCaseCamion _Camion;
        public static WorstCaseCamion Instance
        {
            get
            {
                if (_Camion == null)
                    _Camion = new WorstCaseCamion();
                return _Camion;
            }
        }
        public void Burn(JunkType junkType)
        {
            switch (junkType)
            {
                case JunkType.Plastic:
                    int x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 1;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    Console.WriteLine($"Brucia {junkType}");
                    break;
                default:
                case JunkType.Glass:
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    x = 0;
                    Console.WriteLine($"Brucerà {junkType}");
                    break;
            }
        }
    }
}
